baseURL = "https://bachmeerozean.de"
title = "Bach Meer Ozean"
languageCode = "de-DE"
theme = "indigo"
publishDir = "./public"

[params]
  Author = "Bachmeerozean"
  Description = "authentische Mucke aus Berlin"
  Subtitle = "Deutsch-Pop für die Seele"
	favicon = "static/images/favicon.png"
  Avatar = "images/bmo_logo.png"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "🔗"
  mainSections = ["post"]

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/cover-image.jpg"]

  # Contact/social-network identifiers for social icons
  EmailAddress = "info@bachmeerozean.de"
  # FacebookUser = "FacebookUserName"
  # GitHubUser = "GitHubUserName"
  # RedditUser = "RedditUserName"
  # StackOverflowUser = "StackOverflowUserName"
  # TwitterUser = "TwitterUserName"
  # InstagramUser = "InstagramUserName"
